// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PingaMiPalo.API.Data;

#nullable disable

namespace PingaMiPalo.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PingaMiPalo.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Juguetes para adultos",
                            Name = "Juguetes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ropa íntima sensual",
                            Name = "Lencería"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lubricantes y aceites",
                            Name = "Lubricantes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Accesorios diversos",
                            Name = "Accesorios"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Productos de bienestar íntimo",
                            Name = "Wellness"
                        });
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Vibrador de silicona médica, resistente al agua",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_640.jpg",
                            Name = "Vibrador Clásico",
                            Price = 45.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Lubricante a base de agua, hipoalergénico",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/29/05/45/astronomy-1867616_640.jpg",
                            Name = "Lubricante Premium",
                            Price = 19.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Anillo con vibración, recargable por USB",
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_640.jpg",
                            Name = "Anillo Vibrador",
                            Price = 35.50m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Masajeador de múltiples velocidades, silencioso",
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/12/01/20/28/road-1072821_640.jpg",
                            Name = "Masajeador Personal",
                            Price = 55.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Kit completo para principiantes",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/05/02/37/sunset-1373171_640.jpg",
                            Name = "Kit de Inicio",
                            Price = 89.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Aceite aromático para masajes sensuales",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/02/08/17/24/fantasy-2049567_640.jpg",
                            Name = "Aceite de Masaje",
                            Price = 24.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Vibrador premium con control remoto",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/20/18/35/sunrise-1756274_640.jpg",
                            Name = "Vibrador de Lujo",
                            Price = 125.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Esposas suaves y cómodas",
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/06/19/21/24/avenue-815297_640.jpg",
                            Name = "Esposas de Seda",
                            Price = 29.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Gel con efecto calor/frío",
                            ImageUrl = "https://cdn.pixabay.com/photo/2013/10/02/23/03/mountains-190055_640.jpg",
                            Name = "Gel Estimulante",
                            Price = 22.50m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Bolas de ejercicio Kegel de silicona",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/12/15/13/51/polynesia-3021072_640.jpg",
                            Name = "Bolas Chinas",
                            Price = 38.00m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Velas aromáticas que se convierten en aceite",
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832_640.jpg",
                            Name = "Velas de Masaje",
                            Price = 18.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Plug de silicona suave, tamaño pequeño",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/08/05/26/woman-1807533_640.jpg",
                            Name = "Plug Anal Principiante",
                            Price = 32.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Consolador de silicona con textura realista",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/29/03/53/beach-1867285_640.jpg",
                            Name = "Consolador Realista",
                            Price = 65.00m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Antifaz suave para juegos sensuales",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/11/22/19/15/hand-1850120_640.jpg",
                            Name = "Antifaz de Seda",
                            Price = 15.99m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Description = "Estimulador con tecnología de ondas de presión",
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/09/09/16/05/forest-931706_640.jpg",
                            Name = "Succionador de Clítoris",
                            Price = 95.00m,
                            Stock = 9
                        });
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Email = "admin@pingamipalo.com",
                            ImageUrl = "",
                            PasswordHash = "$2a$11$z8OV.22LgdWOG9CyQOXC6OjEkwBDRhtv3xUQZ3NT4llGdOpUIiWv2",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Email = "invitado@pingamipalo.com",
                            ImageUrl = "",
                            PasswordHash = "$2a$11$frruq4nEyeifJ2bZqN42z.alrnoYEIiJZMHtzyFRTHKitTMzs0qTq",
                            Role = "Invitado",
                            UpdatedAt = new DateTime(2026, 2, 13, 15, 1, 15, 0, DateTimeKind.Utc),
                            Username = "invitado"
                        });
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Order", b =>
                {
                    b.HasOne("PingaMiPalo.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.OrderItem", b =>
                {
                    b.HasOne("PingaMiPalo.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PingaMiPalo.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Product", b =>
                {
                    b.HasOne("PingaMiPalo.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PingaMiPalo.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
